FORMAT: 1A
HOST: http://localhost:1337

# triquiREST

TiquiREST is a simple api to play the clasic game "triqui" online.

# Group Players

## Connected Players Collection [/player]

### List All connected players [GET]

+ Response 200 

        [
            {
                "name":"juan",
                "status":"waiting"
            }, 
            {
                "name":"pedro1",
                "status":"playing"
            }
        ]

### Join player to lobby [POST]


+ Request (application/json)

        {
            "name": "jhon"
        }

+ Response 201 

        {
            "name":"jhon",
            "status":"waiting"
        }
  

## Connected Players notifications Collection [/player/{pid}/notification]  

Pending notification of a given player.

 + Parameters
    + pid (required, number, `1`) ... id of the player.
 

### Get player's pending notifications  [GET]

+ Response 200 

        [
            {
                "id": 1,
                "type":"gameinvite",
                "accepted":false,
                "sender":1
            },
            {
                "id": 2,
                "type":"gameinvite",
                "accepted":true,
                "game":1,
                "sender":2
            }
        ]

### Send notification to player [POST]


+ Request (application/json)

        {
            "type":"gameinvite",
            "sender":2,
            "to":1
        }

+ Response 201

        {
            "notification": [
                {
                  "type": "gameinvite",
                  "sender": 2,
                  "to": 1,
                  "accepted":false,
                  "id": 1
                }
            ]
        }

# Group Notifications

## Connected Players notification [/notification/{id}]

+ Parameters
    + id (required, number, `1`) ... `id` of the notification.

### Accept notification [POST]

+ Request (application/json)

        {
          "accepted":true
        }
    

+ Response 200

        {
          "type": "gameinvite",
          "sender": 2,
          "to": 1,
          "accepted":false,
          "id": 1
        }

### Delete notification  [DELETE]


+ Response 204 



# Group Game

## Active Games collection [/game]

### List all active games [GET]

+ Response 200 

        [
            {
                "id":1,
                "player1":1,
                "player2":2
            }
        ]

### Create new game [POST]

+ Request (application/json)

        {
            "player1":1,
            "player2":2
        }

+ Response 201 

        {
            "id": 1,
            "player1":1,
            "player2":2,
            "board":[
                ["-","-","-"],
                ["-","-","-"],
                ["-","-","-"]
            ],
            "playerTurn":1
        }

## Active game [/game/{id}]

+ Parameters
    + id (required, number, `1`) ... `id` of the game.

### Get detailled game [GET]

+ Response 200

        {
            "id": 1,
            "player1":1,
            "player2":2,
            "board":[
                ["-","-","-"],
                ["-","-","-"],
                ["-","-","-"]
            ],
            "playerTurn":1
        }

### Update Game [POST]

+ Request (application/json)

        {
            "id":1,
            "board":[
                ["x","-","-"],
                ["-","-","-"],
                ["-","-","-"]
            ],
            "playerTurn":2
        }

+ Response 200

        {
            "id": 1,
            "player1":1,
            "player2":2,
            "board":[
                ["x","-","-"],
                ["-","-","-"],
                ["-","-","-"]
            ],
            "playerTurn":1
        }

### Delete Game [DELETE]

+ Response 204